### ISSUE TITLE
There is no JasperViewerFX in the Dependencie! How to add this?

### ISSUE THREAD

**Issue by ahmeedev** [gbfragoso/JasperViewerFX#4]
![image](https://user-images.githubusercontent.com/75003816/121148898-9c9c4c00-c85b-11eb-91a7-212f8948a032.png)

i use this one... 
 implementation 'net.sf.jasperreports:jasperreports:6.13.0'

**Comment by gbfragoso** [comment]
You need to set JasperReports on project dependencies (with maven or something else) and copy JasperViewerFX class to your project. JasperViewerFX isn't part of JasperResport library.  Look this JavaFX example: https://github.com/gbfragoso/biblioteca/tree/master/src/main/java/org/casadeguara/componentes

**Comment by ahmeedev** [comment]
@gbfragoso  
A bundle of thanks.. but now, I am facing a new issue .. Can you guide me.


![image](https://user-images.githubusercontent.com/75003816/121673421-4b45c400-caca-11eb-9fff-bd6d82b525da.png)


I'm giving both the .jasper URL && .jrxml one by one.. but both of them give this error.

**Comment by gbfragoso** [comment]
This question is not related with JasperViewerFX but the getClass().getResource() method searches for project's local resources. I recommend you read this thread: https://stackoverflow.com/a/50230042/13019367

**Comment by ahmeedev** [comment]
@gbfragoso  
I read all of this and correct this issue but now I'm got a new issue

![image](https://user-images.githubusercontent.com/75003816/121768269-e09e9200-cb76-11eb-9d57-b92966df8e87.png)
