### ISSUE TITLE
Trouble with printAction

### ISSUE THREAD

**Issue by prguser** [gbfragoso/JasperViewerFX#5]
Hi gbfragoso,

when I execute printAction occurs an error if true parameter of JasperPrintManager.printReport is set and don´t show print dialog to choice of a printer: 
net.sf.jasperreports.engine.JRException: Error printing report.
	at net.sf.jasperreports.engine.print.JRPrinterAWT.printPages(JRPrinterAWT.java:215)

Thank you in advance

**Comment by gbfragoso** [comment]
Hi prguser, with this information i can't help you. To be clear, JasperViewFX is a "third-party plugin" and is not related with JasperReports. I don't answer any questions about JasperReports itself, only JasperViewFX. The right way to call JasperViewFX is:

```
        Connection con = new ConnectionManager().getConnection();
	JasperReport jreport = (JasperReport) JRLoader.loadObject(getClass().getResource("your_resource_path"));
	JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
	new JasperViewerFX(primaryStage).viewReport("Simple report", jprint);
	con.close();`
```
